### ISSUE TITLE
libiberty.a no such file or directory

### ISSUE THREAD

**Issue by tsparber** [sampsyo/homebrew-mspgcc#10]
I had a problem, with the File.unlink as my libiberty.a was not in a subfolder x86_64.

```
/usr/local/Library/Taps/sampsyo/homebrew-mspgcc/msp430-gcc.rb:51:in `unlink'
Errno::ENOENT: No such file or directory - /usr/local/Cellar/msp430-gcc/4.7.0/lib/x86_64/libiberty.a
```

The patch in https://github.com/larsimmisch/homebrew-avr/commit/8cc2a2e591b3a4bef09bd6efe2d7de95dfd92794 would check for that (using gcc) but my gcc does not have the option --print-multi-os-dir so this is only a workaround.

```
      if File.exists?("#{prefix}/lib/x86_64/libiberty.a")
        File.unlink "#{prefix}/lib/x86_64/libiberty.a"
      else
        File.unlink "#{prefix}/lib/libiberty.a"
      end
```

**Comment by tsparber** [comment]
hmm, this sems to be a duplicate of #3 which looks like a better solution, but has been reverted in https://github.com/sampsyo/homebrew-mspgcc/commit/154da1ed517a0e226297121e6ba46c0fd3b676e8#diff-839533bbb33c5e4b20549fd2d42664bfR49 :confused:

**Comment by sampsyo** [comment]
Thanks for the fix, @tsparber.
